import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


function Navbar() {
    return (
        <nav className="w-full border-b px-6 py-4">
            <div className="max-w-6xl mx-auto flex items-center justify-between">
                <span className="text-xl font-bold">StudujChytře.cz</span>

                <ul className="flex gap-6 text-sm">
                    <Link href="/">
                        <li className="hover:underline cursor-pointer">Home</li>
                    </Link>
                    <Link href="/learn">
                        <li className="hover:underline cursor-pointer">Learn</li>
                    </Link>
                    <Link href="/about">
                        <li className="hover:underline cursor-pointer">About</li>
                    </Link>
                    <Link href="/login" className="hover:underline">
                        Login
                    </Link>

                </ul>
            </div>
        </nav>
    );
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        {children}
        </body>
        </html>
    );
}
